name: JMeter Test

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  run-jmeter-test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Run JMeter test
      shell: cmd
      run: |
        call "C:\\Users\\RachanaMohta\\Downloads\\apache-jmeter-5.6.3\\bin\\jmeter.bat" -n -t "C:\\Users\\RachanaMohta\\Downloads\\apache-jmeter-5.6.3\\bin\\petsStore.jmx" -l "C:\\Users\\RachanaMohta\\Downloads\\result.jtl" -JcsvFile1="C:\\Users\\RachanaMohta\\Desktop\\petsLogin.csv" -JcsvFile2="C:\\Users\\RachanaMohta\\Desktop\\pets.csv"
        
    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-results
        path: C:\\Users\\RachanaMohta\\Downloads\\result.jtl
